"""create phone column

Revision ID: e425017da9d0
Revises:
Create Date: 2026-07-28 19:27:14.182519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e425017da9d0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bank_transactions", "category_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint(
        op.f("bank_transactions_category_id_fkey"),
        "bank_transactions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "bank_transactions",
        "bank_categories",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("users", sa.Column("phone", sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, "users", ["phone"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "phone")
    op.drop_constraint(None, "bank_transactions", type_="foreignkey")
    op.create_foreign_key(
        op.f("bank_transactions_category_id_fkey"),
        "bank_transactions",
        "bank_categories",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "bank_transactions", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
