"""empty message

Revision ID: 4b02939ce61a
Revises: d3e340ec962f
Create Date: 2026-07-29 19:27:30.945769

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4b02939ce61a"
down_revision: Union[str, Sequence[str], None] = "d3e340ec962f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "financial_budget",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("budget_allocated", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["bank_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("financial_budget")
    # ### end Alembic commands ###
