"""empty message

Revision ID: d3e340ec962f
Revises: f3b83a85ff0a
Create Date: 2026-07-29 19:10:09.144417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e340ec962f'
down_revision: Union[str, Sequence[str], None] = 'f3b83a85ff0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial_budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_budget',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('budget_allocated', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['bank_categories.id'], name=op.f('financial_budget_category_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('financial_budget_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('financial_budget_pkey'))
    )
    # ### end Alembic commands ###
